### Create User Role

POST localhost:9000/users/roles
Content-Type: application/json

{
  "role": "NORMAL_USER"
}


### Register User

POST localhost:9000/users
Content-Type: application/json

{
    "email": "john@email.com",
    "password": "test",
    "firstName": "John",
    "lastName": "Snow",
    "dateOfBirth" : "29/03/1997",
    "phoneNumber": "086-123-4567"
}

### Verify Email
POST localhost:9000/users/verify-email
Content-Type: application/json

{
  "email": "john@email.com",
  "token": "zljzPXki250239283258887501963edd"
}

### Login
POST localhost:9000/users/login
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "test"
}

