server:
  port: 9000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingSystem
    username: postgres
    password: secret
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConnPool
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: e90f22b03dc390
    password: 5c95f70aed9e97
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

security:
  jwt:
    secret-key: 295980db37e0792499daa34fc05281ea6102fc99dd8a7e971455795ff56aaab1
    expiration: 300000 # 10 minutes
    refresh-token:
      expiration: 7200000 # 2 hours
